### PR TITLE
chore: add basic configuration

### PR DESCRIPTION
**Pull request by adriexnet**
### What does this PR do?
- Add the basic configuration for hapi and hasura

### How should this be tested?
- checkout the project
- create your .env file
- source .env && docker-compose up --build
- open http://localhost:8080 and http://localhost:9090

### CODE REVIEW

**Comment by xavier506** [comment]
@adriexnet  Awesome work!

Just a few questions , are we using the same `prettierrc` and `linter` settings consistently across services and the frontend boilerplate?

Also I noticed you included some table migrations , are we going to need those as part of the boilerplate? Most users are gong to end up with a migration to create and then eliminate those tables.

**Review by xavier506 — APPROVED** [review]

**Comment by adriexnet** [comment]
@xavier506 yes I set the same configuration for prettier and also using the same linters `standard` and `prettier`

I added a few migrations as example of how to integrate the custom logic from hapi with hasura using actions and setup the permissions for guest user but you are right most users will eliminate those migrations, probably we should remove it and add a new section in the readme to explain how to use the boilerplate

**Comment by rubenabix** [comment]
@adriexnet please remove `sequelize` module
@kecoco16 I think is important to add `graphql-request`
@adriexnet I would like to add a `makefile` to simplify the docker execution

**Review by rubenabix — APPROVED** [review]

**Comment by adriexnet** [comment]
> @adriexnet please remove `sequelize` module
> @kecoco16 I think is important to add `graphql-request`
> @adriexnet I would like to add a `makefile` to simplify the docker execution

@rubenabix Thanks for the comments

**Pull request merged**
